export const CHANGE_TAB = "CHANGE_TAB";

export const SET_NEW_EXPENSE_MODAL = "SET_NEW_EXPENSE_MODAL";

export const SET_NEW_RECURRING_EXPENSE_MODAL =
  "SET_NEW_RECURRING_EXPENSE_MODAL";

export const SET_DELETE_MODAL = "SET_DELETE_MODAL";

export const SET_PREVIOUS_ENTRY = "SET_PREVIOUS_ENTRY";

export const CHANGE_TOTAL = "CHANGE_TOTAL";
